# This is a basic workflow to help you get started with Actions

name: Testing vault

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ self-hosted, Linux, ARM64 ]
    permissions:
        contents: read
        id-token: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        id: secrets
        with:
          url: https://vault.tenzin.io
          method: jwt
          role: github-actions-runner-role
          secrets: |
              secret/data/mysecret secret_one | SECRET_ONE ;
              /artifactory/token/publish access_token | JF_GITHUB_ACTIONS_TOKEN ;

      - name: Read SECRET_ONE
        run: "echo '${{ steps.secrets.outputs.SECRET_ONE }}'"
        
      - name: Read JF_GITHUB_ACTIONS_TOKEN
        run: "echo '${{ steps.secrets.outputs.JF_GITHUB_ACTIONS_TOKEN }}'"
        

